# Generated by Django 4.2.7 on 2023-11-14 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profiles_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='path',
        ),
    ]
