# Generated by Django 4.2.7 on 2024-01-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_individual_pricing_delete_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20000)),
                ('plan_type', models.CharField(max_length=20000)),
                ('orignal_price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=50)),
                ('vat_price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('orignal_cost_per_user', models.DecimalField(decimal_places=2, max_digits=50)),
                ('current_cost_per_user', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
        ),
    ]
