# Generated by Django 4.2.7 on 2024-01-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_business_pricing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_pricing',
            name='current_cost_per_user',
        ),
        migrations.RemoveField(
            model_name='business_pricing',
            name='orignal_cost_per_user',
        ),
        migrations.AddField(
            model_name='business_pricing',
            name='current_cost_per_extra',
            field=models.DecimalField(decimal_places=5, default=2.0, max_digits=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business_pricing',
            name='orignal_cost_per_extra',
            field=models.DecimalField(decimal_places=5, default=2.0, max_digits=50),
            preserve_default=False,
        ),
    ]
